dataset_keys: [ "train", "validation", "test" ]
common:
  sequence_length: 1.0  # seconds
  sequence_dt: 0.0001  # seconds
  sequence_dstep: 100  # run callback each 100 simulation steps
  rod_num_elements: 25
  rod_start_position: [ 0.0, 1.0, 0.0 ]
  rod_direction: [ 0.0, 0.0, 1.0 ]
  rod_normal: [ 0.0, 1.0, 0.0 ]
  rod_base_length: 1.0
  rod_base_radius: 0.025
  save_random_samples_gifs: true

train:
  num_sequences: 1000
  rod_density_range: [ 1000, 1300 ]  # density of rod (kg/m^3)
  rod_energy_dissipation_range: [ 0.0001, 0.005 ]  # Energy dissipation of rod
  rod_youngus_modulus_range: [ 100000, 1000000 ] # Elastic Modulus (Pa)
  rod_poisson_ratio: [ 0.3, 0.5 ] # Poisson Ratio
  rod_origin_force_range: [ [ -10.0, 9.0, -10.0 ], [ 10.0, 10.0, 10.0 ] ] # Forces applied to the origin node
  rod_end_force_range: [ [ -10.0, 9.0, -10.0 ], [ 10.0, 10.0, 10.0 ] ] # Forces applied to the endpoint

validation:
  num_sequences: 100
  rod_density_range: [ 1000, 1300 ]  # density of rod (kg/m^3)
  rod_energy_dissipation_range: [ 0.0001, 0.005 ]  # Energy dissipation of rod
  rod_youngus_modulus_range: [ 100000, 1000000 ] # Elastic Modulus (Pa)
  rod_poisson_ratio: [ 0.3, 0.5 ] # Poisson Ratio
  rod_origin_force_range: [ [ -10.0, 9.0, -10.0 ], [ 10.0, 10.0, 10.0 ] ] # Forces applied to the origin node
  rod_end_force_range: [ [ -10.0, 9.0, -10.0 ], [ 10.0, 10.0, 10.0 ] ] # Forces applied to the endpoint

test:
  num_sequences: 100
  rod_density_range: [ 1300, 1500 ]  # density of rod (kg/m^3)
  rod_energy_dissipation_range: [ 0.005, 0.01 ]  # Energy dissipation of rod
  rod_youngus_modulus_range: [ 1000000, 10000000 ] # Elastic Modulus (Pa)
  rod_poisson_ratio: [ 0.5, 0.7 ] # Poisson Ratio
  rod_origin_force_range: [ [ -10.0, 9.0, -10.0 ], [ 10.0, 10.0, 10.0 ] ] # Forces applied to the origin node
  rod_end_force_range: [ [ -10.0, 9.0, -10.0 ], [ 10.0, 10.0, 10.0 ] ] # Forces applied to the endpoint