simulation_timestep: 0.01666666666  # simulation settings
simulation_action_steps: 150
simulation_use_gui: False
realtime: False

plane_position: [ 0, 0, 0 ]  # plane settings
plane_quaternion: [ 0, 0, 0, 1 ]

pusher_radius: 0.9 # pusher settings
pusher_height: 0.0
pusher_link_mass: 0.5
pusher_lin_vel: 1.0

object_position: [ 0, 0, 0.3 ] # object settings
object_quaternion: [ 0, 0, 0, 1 ]
object_size_mean: 0.4
object_size_sigma: 0.1
object_mass_mean: 2.0
object_mass_sigma: 0.9
object_friction_mean: 1.0
object_friction_sigma: 0.5
object_restitution_mean: 1.0
object_restitution_sigma: 0.5
object_spring_stiffness_mean: 700.0
object_spring_stiffness_sigma: 350.0
object_elastic_stiffness_mean: 700.0
object_elastic_stiffness_sigma: 350.0
object_pybullet_rgba_color: [1, 0, 0, 1]
object_color_threshold_low: [100, 0, 0]
object_color_threshold_high: [255, 50, 50]

cam_target_pos: [ 0.0, 0.0, 1.0 ]  # camera settings
cam_roll: 0.0 # deg
cam_pitch: -90.0
cam_yaw: 0.0
cam_distance: 3.0
projection_w: 640
projection_h: 480
near_plane: 0.01
far_plane: 100
fov: 60

num_outputs: 4 # haptic regression network
batch_size: 1
action_kernel_size: 3
dropout: 0.8
lstm_units: 32
lstm_stateful: True
load_path: '/home/mbed/Projects/rl-physnet/scripts/logs_offline'

termination_reward: 10.0 # RL
time_penalty_init: 0.0
time_penalty_delta: 0.5
termination_steps: 30